-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

-- monitor=,preferred,auto,auto

-- monitor = NAME, RESOLUTION@REFRESH, POSITION, SCALE

hl.monitor({
    output   = "DP-2",
    mode     = "1920x1080@144",
    position = "1080x0",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60",
    position = "0x0",
    scale    = 1,
    transform = 1,
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local terminal = "ghostty"

local fileManager = "dolphin"

local menu = "walker"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = waybar & hyprpaper & firefox






--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = {
            top = 10,
            right = 20,
            bottom = 20,
            left = 20
        },
        border_size = 2,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    layout = {
        single_window_aspect_ratio = "4 3",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 0.85,
        inactive_opacity = 0.6,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = false
        -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
        --        NAME,           X0,   Y0,   X1,   Y1
        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/
        --           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    },
})

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

hl.workspace_rule({
    workspace = "special:magic",
    gaps_out = {
        top = 30,
        right = 150,
        bottom = 30,
        left = 150
    }
})

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrule = bordersize 0, floating:0, onworkspace:f[1]

-- windowrule = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = 0,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true,
        -- If true disables the random hyprland logo / anime girl background.
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        -- kb_variant = {  },
        -- kb_model = {  },
        -- kb_options = {  },
        -- kb_rules = {  },
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures


-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

-- hl.device({
--     name = "epic-mouse-v1",
--     sensitivity = -0.5,
-- })

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "ALT"

hl.bind("SUPER" .. " + " .. "V", hl.dsp.exec_cmd("walker --provider clipboard"))

hl.bind("SUPER + ALT + SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("grim - | wl-copy"))

hl.bind("SUPER + SHIFT" .. " + " .. "S", hl.dsp.exec_cmd('grim -g "$(slurp -d)" - | wl-copy'))

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "SUPER" .. " + " .. "P", hl.dsp.exec_cmd("ghostty"))

hl.bind(mainMod .. " + " .. "SUPER" .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SUPER" .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "SUPER" .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

hl.bind(mainMod .. " + " .. "SUPER" .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd("walker"))

hl.bind(mainMod .. " + equal", hl.dsp.layout("splitratio 0.05"))

hl.bind(mainMod .. " + minus", hl.dsp.layout("splitratio -0.05"))

-- bind = $mainMod SUPER, P, pseudo, # dwindle

hl.bind(mainMod .. " + " .. "comma", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(mainMod .. " + " .. "SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

-- Move windows with SUPER + Left Mouse button

hl.bind("SUPER" .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

-- Resize windows with SUPER + Right Mouse button

hl.bind("SUPER" .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- Move windows with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.move({ direction = "l" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.move({ direction = "u" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.move({ direction = "d" }))

-- hl.bind(mainMod .. " + SHIFT + SUPER + H", hl.dsp.workspace.move("l"))
-- hl.bind(mainMod .. " + SHIFT + SUPER + L", hl.dsp.workspace.move("r"))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "A", hl.dsp.focus({ workspace = "name:A" }))

hl.bind(mainMod .. " + " .. "B", hl.dsp.focus({ workspace = "name:B" }))

hl.bind(mainMod .. " + " .. "C", hl.dsp.focus({ workspace = "name:C" }))

hl.bind(mainMod .. " + " .. "D", hl.dsp.focus({ workspace = "name:D" }))

hl.bind(mainMod .. " + " .. "E", hl.dsp.focus({ workspace = "name:E" }))

hl.bind(mainMod .. " + " .. "F", hl.dsp.focus({ workspace = "name:F" }))

hl.bind(mainMod .. " + " .. "G", hl.dsp.focus({ workspace = "name:G" }))

hl.bind(mainMod .. " + " .. "I", hl.dsp.focus({ workspace = "name:I" }))

hl.bind(mainMod .. " + " .. "M", hl.dsp.focus({ workspace = "name:M" }))

hl.bind(mainMod .. " + " .. "N", hl.dsp.focus({ workspace = "name:N" }))

hl.bind(mainMod .. " + " .. "O", hl.dsp.focus({ workspace = "name:O" }))

hl.bind(mainMod .. " + " .. "P", hl.dsp.focus({ workspace = "name:P" }))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.focus({ workspace = "name:Q" }))

hl.bind(mainMod .. " + " .. "R", hl.dsp.focus({ workspace = "name:R" }))

hl.bind(mainMod .. " + " .. "T", hl.dsp.focus({ workspace = "name:T" }))

hl.bind(mainMod .. " + " .. "U", hl.dsp.focus({ workspace = "name:U" }))

hl.bind(mainMod .. " + " .. "V", hl.dsp.focus({ workspace = "name:V" }))

hl.bind(mainMod .. " + " .. "W", hl.dsp.focus({ workspace = "name:W" }))

hl.bind(mainMod .. " + " .. "Y", hl.dsp.focus({ workspace = "name:Y" }))

hl.bind(mainMod .. " + " .. "X", hl.dsp.focus({ workspace = "name:X" }))

hl.bind(mainMod .. " + " .. "Z", hl.dsp.focus({ workspace = "name:Z" }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "A", hl.dsp.window.move({ workspace = "name:A" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "B", hl.dsp.window.move({ workspace = "name:B" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "C", hl.dsp.window.move({ workspace = "name:C" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.window.move({ workspace = "name:D" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.window.move({ workspace = "name:E" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.move({ workspace = "name:F" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.window.move({ workspace = "name:G" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.window.move({ workspace = "name:I" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.window.move({ workspace = "name:M" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.window.move({ workspace = "name:N" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "O", hl.dsp.window.move({ workspace = "name:O" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.window.move({ workspace = "name:P" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.move({ workspace = "name:Q" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.window.move({ workspace = "name:R" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.window.move({ workspace = "name:T" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "U", hl.dsp.window.move({ workspace = "name:U" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.window.move({ workspace = "name:V" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.window.move({ workspace = "name:W" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Y", hl.dsp.window.move({ workspace = "name:Y" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "X", hl.dsp.window.move({ workspace = "name:X" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Z", hl.dsp.window.move({ workspace = "name:Z" }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n1 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule

-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.

--windowrulev2 = suppressevent maximize, class:.*

-- Fix some dragging issues with XWayland

--windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("elephant")
    hl.exec_cmd("udiskie --tray &")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("awww img /home/kai/wallpapers/cats_lazin.gif")
    hl.exec_cmd("swww init")
end)
